name: ascii job generator 
on: push 

jobs: 
    ascii-job: 
        runs-on: ubuntu-latest 
        steps: 
            - name: checkout the repo 
              uses: actions/checkout@v4

            - name: eexecute shell script
              run: bash install-and-run-cowsay.sh
              

              

