name: ahlilou first workflow

on: push 

jobs: 
    first-job: 
        runs-on: ubuntu-latest
        steps:
            - name: checkout 
              uses: actions/checkout@v4
            - name: salam alaykoum
              run: |
               echo "Salam alaykoum"
               echo "Wa alaykoum assalam"
            - name: list files 
              run: ls
            - name: display file 
              run: cat README.md  
              


