name: test multiple jobs 
on: workflow_dispatch
env: 
    FILE_TO_DOWNLOAD: show.txt 
jobs: 
    first-job: 
        runs-on: ubuntu-latest
        steps:
            - name: install cowsay 
              run: sudo apt install cowsay
            - name: generate cowsay 
              run: cowsay  'Hello, world!' > $FILE_TO_DOWNLOAD 
            - name: display 
              run: cat $FILE_TO_DOWNLOAD  
            - name: upload artifacts  
              uses: actions/upload-artifact@v4
              with:
                 name: cowsay
                 path: $FILE_TO_DOWNLOAD 
    second-job: 
        needs: first-job
        runs-on: ubuntu-latest
        steps: 
            - name: download artifacts 
              uses: actions/download-artifact@v4
              with:
                name: cowsay
            - name: display the file 
              run: cat $FILE_TO_DOWNLOAD  
    third-job: 
        needs: [first-job]
        runs-on: ubuntu-latest 
        steps: 
            - name: download artifacts 
              uses: actions/download-artifact@v4
              with:
                name: cowsay
            - name: list files 
              run: ls -altr    
